version: "3.9"
services:
    app:
        build:
            args:
                user: ${USER:-user}
                uid: ${UID:-1000}
            context: ./
            dockerfile: ./docker/app/Dockerfile
        container_name: centralbank-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME:-centralbank}
            XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST:-172.17.0.1} client_port=${XDEBUG_STORM_PORT:-9003}
        networks:
            - centralbank

    nginx:
        image: nginx:alpine
        container_name: central-bank-nginx
        ports:
            - ${DOCKER_WEB_PORT:-8000}:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - centralbank

networks:
    centralbank:
        driver: bridge

volumes:
    dbdata:
