version: "3.9"
services:
    app:
        build:
            args:
                user: ${USER:-user}
                uid: ${UID:-1000}
            context: ./
            dockerfile: ./docker/app/Dockerfile
        container_name: centralbank-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME:-centralbank}
            XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST:-172.17.0.1} client_port=${XDEBUG_STORM_PORT:-9003}
        networks:
            - centralbank

    nginx:
        image: nginx:alpine
        container_name: centralbank-nginx
        ports:
            - ${DOCKER_WEB_PORT:-8000}:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - centralbank

    redis:
        image: redis:7.2.1-alpine3.18
        container_name: centralbank-redis
        ports:
            - ${DOCKER_REDIS_PORT:-6379}:6379
        volumes:
            - redis:/data
        command: redis-server --appendonly yes
        networks:
            - centralbank

    rabbitmq:
        image: 'rabbitmq:3.9.29-management-alpine'
        container_name: centralbank-rabbitmq
        ports:
            - '${DOCKER_AMQP_PORT:-5672}:5672'
            - '${DOCKER_RABBITMQ_MC_PORT:-15672}:15672'
        environment:
            RABBITMQ_DEFAULT_USER: ${DOCKER_RABITMQ_USER:-rabbit}
            RABBITMQ_DEFAULT_PASS: ${DOCKER_RABITMQ_PASSWORD:-rabbit}
        volumes:
            - rabbitmq:/var/lib/rabbitmq:cached
        networks:
            - centralbank

    app-consumer:
        build:
            args:
                user: ${USER:-user}
                uid: ${UID:-1000}
            context: ./
            dockerfile: ./docker/app/Dockerfile
        container_name: centralbank-app-consumer
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
        entrypoint: '/bin/bash /var/www/docker/app/consume_entrypoint.sh'
        networks:
            - centralbank

networks:
    centralbank:
        driver: bridge

volumes:
    dbdata:
    rabbitmq:
    redis:
        driver: local
